Traceback (most recent call last):
  File "/home/kevin/github/automate-the-boring/raise-exception.py.py", line 4, in <module>
    raise Exception('This is an error message.')
Exception: This is an error message.
